### ISSUE TITLE
Adding it to fixes.inc

### ISSUE THREAD

**Issue by NexiusTailer** [RogueDrifter/Silent-teleport-bugfix-inc-#1]
Hello, it's pretty important fix and I think it would be great if it would be added in fixes.inc (preserving all the credits of course).

https://github.com/Open-GTO/sa-mp-fixes/issues/92

**Comment by RogueDrifter** [comment]
Oh wew it took me a long time to see this, i really don't mind at all if you want to do it yourself or have y_less do it or me, just lemme know whenever!

**Comment by RogueDrifter** [comment]
Done.
